export const ARTICLE_ADD = 'ARTICLE_ADD';
export const ARTICLE_CLICK = 'ARTICLE_CLICK';
export const ARTICLE_LIST_UPDATE = 'ARTICLE_LIST_UPDATE';
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_CLICK = 'CATEGORY_CLICK';
export const CATEGORY_LIST_UPDATE = 'CATEGORY_LIST_UPDATE';
